### PR TITLE
Fix build with LibreSSL

### PR DESCRIPTION
**Pull request by Sp1l**

### CODE REVIEW

**Comment by Sp1l** [comment]
openxpki relies on openssl version output which makes builds with LibreSSL fail. Attached patch fixes this.

**Comment by svysh** [comment]
Please allow a day or so for me to perform formal testing of openxpki with openssl vs openxpki with libressl. Gost and non-gost features.

**Comment by svysh** [comment]
Let us forget about GOST for a while. 
I populated a fresh (empty) jail with libressl on freebsd-10.1 with settings:
WITH_OPENSSL_PORT=yes
OPENSSL_PORT=security/libressl

I hacked openxpki to skip checks of the openssl version.
The latest openxpki does not build with libressl:

====> Running Q/A tests (stage-qa)
Warning: /wrkdirs/usr/ports/security/p5-openxpki/work/stage/usr/local/lib/perl5/site_perl/mach/5.18/auto/OpenXPKI/OpenXPKI.so is not linked with libperl.so.5.18, not respecting lddlflags?
Error: None of the .so in /wrkdirs/usr/ports/security/p5-openxpki/work/stage/usr/local/lib/perl5/site_perl/mach/5.18 are linked with libperl.so.5.18, see above for the full list.
*** Error code 1
Stop.
make: stopped in /usr/ports/security/p5-openxpki
====>> Error: stage-qa failures detected

openxpki is a rare example of software which uses most of the features of the openssl suite.
Including low level functions, which even are not documented in some cases.
Expecting a major work needed to support libressl here.

**Comment by svysh** [comment]
openxpki-0.27 builds ok with libressl-2.1.6 and perl-5.18.4
on FreeBSD-10.1. Used a slightly hacked (skip checks of the openssl name and version, as Bernard suggested) port security/p5-openxpki. Moreover, all built-in openxpki tests pass ok.

Except GOST related openxpki tests. But let us forget about them for a while. Need to investigate this GOST issue.

Oliver, if you decide to merge the patch of Bernard, please make notice how github's tester is unhappy about it.

**Comment by oliwel** [comment]
Thank you for the patch, it was included in d6605c2862b6f04879c0e183264a2c8f20a6357d
Please note that we did no full test against LibreSSL and as we use a binding interface and call internal methods of the openssl libs chances are high that it is not working  - if you can provide support in porting this code, you are welcome to join the development team.

**Comment by Sp1l** [comment]
I believe there was still an error in my patch, my apologies... Should have done a real one instead of adding it via Web-UI...

You should want to check the patch-version as well, hopefully no-one using OpenSSL 1.0.2 which was the first released 1.0.2.

Patch looks a lot better than my hacky one :D
Not being a user of openxpki myself I can try and help fix failures where they arise. You may want to check https://wiki.freebsd.org/LibreSSL and the sub-page with known fixes. Let me know if you find anything!

**Pull request closed without merging**
