### PR TITLE
Fix LibreSSL- and -version detection

### PR DESCRIPTION
**Pull request by Sp1l**
Was almost correct...
LibreSSL uses X.Y.Z numbering only whereas OpenSSL uses X.Y.Za numbering (apart from first release of X.Y.Z).
This patch fixes detection of LibreSSL and the version yet keeps OpenSSL detection as intended.
OpenSSL 0.9.8zf
OpenSSL 1.0.1m
OpenSSL 1.0.2
LibreSSL 2.0.5
LibreSSL 2.1.6

OpenSSL version: major=2, minor=1, fix=6
Warning: LibreSSL found, support for LibreSSL is experimental!All modules will be installed.

OpenSSL version: major=1, minor=0, fix=1, patch=l
All modules will be installed.

OpenSSL version: major=1, minor=0, fix=2, patch=a
All modules will be installed.
(OpenSSL 1.0.2 was skipped on FreeBSD, port was upgraded from 1.0.1m to 1.0.2a)

### CODE REVIEW

**Comment by svysh** [comment]
Without a fix like this, build of openxpki-0.28.0 breaks if encounters today's libressl-2.1.6.

**Comment by oliwel** [comment]
I will publish a new release hopefully end of this week which will contain this merge. Can you confirm that this fix on top of current develop works?

**Comment by oliwel** [comment]
@Sp1l  can you please make pull requests against develop next time, that will speed up integration.

**Comment by svysh** [comment]
Hi Oliver. For me it looks like the latest today's commit to develop (edcec2e4c005773f5c83bce77fca17fde0c813d5) is empty. It says:
"Showing 0 changed files with 0 additions and 0 deletions."
At least it does not modify the file in question ..../Makefile.PL. What I am doing wrong?

**Comment by svysh** [comment]
Meanwhile, yes I can confirm. Develop brunch (edcec2e) builds ok with libressl-2.1.6. Moreover, tests say PASS, although with lots of warnings.

**Comment by svysh** [comment]
And you may want to terminate a message with "\n" in line 118 of ..../Makefile.PL

**Comment by Sp1l** [comment]
Thanks @oliwel! Will try and remember if I create a next patch for OpenXPKI to patch the develop branch instead. (If you had told me earlier I'd have rerolled the patch for that branch :D)

**Pull request merged**
